# Generated by Django 4.0.6 on 2022-08-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_groupstudents_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Croups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
