# Generated by Django 4.0.6 on 2022-08-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_croups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Croups',
        ),
    ]
